%% CODE FOR IMPLEMENTATION OF THE INVERTED PENDULUM MODEL:
%  FREDERICO CASARA ANTONIAZZI - 12/03/2024
%  IMPLEMENTATION OF THE PENDULUM MODEL USED IN A S-FUNCTION LEVELS 1 AND 2
%  IN SIMULINK

function dx = pendulum(t, x, u)

l = .5;    % LENGHT OF THE ROD
m = .1;    % MASS OF THE PENDULUM
g = 9.81;  % ACCELERATION OF GRAVITY
b = 25e-3; % FRICCTION COEFFICIENT

dx(1) = x(2);
dx(2) = -(g/l)*sin(x(1)) -(b/(m*l^2))*x(2) + (1/(m*l^2))*u; 

end
