% FUNCTION FOR PLOTTING THE PROJECT OF CONTROLLER FOR FULL-STATE FEEDBACK:
function plottingFSFB(Controller)

% OPENING THE STRUCTURE OF CONTROLLER WITH ALL THE SYSTEM'S INFORMATION

% PLOTTING THE RESULTS FOR FURTHER ANALYSIS:
plot(Controller, Controller);

end