%% FREDERICO CASARA ANTONIAZZI
%  CODE FOR POLAR PLOTS IN A CARDIOID MICROPHONE
%  SEVENTH CODE IN PROGRAMMING WITH MATLAB OF CHAPMAN SECOND EDITION

%% INITIAL DEFINITIONS:

clear
close all
clc

format short

%% PURPOSE OF THE CODE:

% THIS PROGRAM PLOTS THE GAIN PATTERN OF A CARDIOID MICROPHONE.

% VARIABLES:
%   g     -> MICROPHONE GAIN CONSTANT
%   gain  -> GAIN AS A FUNCTION OF ANGLE
%   theta -> ANGLE FROM MICROPHONE AXIS (rad)

%% MAIN CODE:

g = 0.5; % CONSTANT OF THE MICROPHONE SELECTED

theta = 0:pi/20:2*pi; % VARIATION OF THE ANGLE

% CALCULATIONG THE GAIN VERSUS ANGLE:
gain = 2*g*(1 + cos(theta));

% PLOTTING THE RESULT:
polarplot(theta, gain, 'r-');
title('\bfGain versus \theta');
