%%  FREDERICO CASARA ANTONIAZZI
%   CODE IMPLEMENTED FOR C-14 DATE OF A ORGANIC SAMPLE
%   TRHID CODE IN PROGRAMMING WITH MATLAB OF CHAPMAN SECOND EDITION

%% INITIAL DEFINITIONS:

clear
close all
clc

format short

%% PURPOSE OF THE CODE:

% TO CALCULETE AND AGE OF AN ORGANIC SAMPLE FROM THE PERCENTAGE OF THE
% ORIGINAL CARBON 14 REMAINING IN THE SAMPLE

% VARIABLES:
%   age     -> THE AGE OF THE SAMPLE IN YEARS (Y)
%   lambda  -> THE RADIOACTIVE DECAY CONSTANT FOR C_{14} IN UNITS OF 1/Y
%   percent -> THE PERCENTAGE OF C_{14} REMAINING AT THE TIME OF THE MEASUREMENT
%   ratio   -> THE RATIO OF THE C_{14} REMAINING
%   string  -> OUTPUT TO INFORME THE AGE OF THE SAMPLE

%% MAIN CODE:

% DECLARING THE VARIABLES:
lambda = 0.00012097; % DECAY CONSTANT FOR C_{14}

% ASKING THE PERCENTAGE REMAINING OF C_{14} IN THE SAMPLE:
percent = input('ENTER THE PERCENTAGE OF C_14 REMAINING: ');

% PERFORME CALCULATIONS:

ratio = percent/100;          % CONVERT TO FRACTIONAL RATIO
age = (-1/lambda)*log(ratio); % GETTING THE AGE IN YEARS

% INFORMING THE AGE OF THE SAMPLE:

string = ['THE AGE OF THE SAMPLE IS ', num2str(age), ' YEARS.'];
disp(string);
