%% FREDERICO CASARA ANTONIAZZI
%  CODE FOR THE FACTORIAL FUNCTION
%  ELEVENTH CODE IN PROGRAMMING WITH MATLAB OF CHAPMAN SECOND EDITION

%% INITIAL DEFINITIONS:

clear
close all
clc

format short
 
%% PURPOSE OF THE CODE:

% CALCULATE THE FACTORIAL OF THE ENTERED NUMBER

% VARIABLES:
%   n           -> THE NUMBER OF THE FACTORIAL
%   n_factorial -> THE RESULT OF THE OPERATION OF FACTORIAL IN A REAL POSITIVE NUMBER

%% MAIN CODE:

n_factorial = 1; % THE VARIABLE FOR STORE THE ANSWER

% READ IN FIRST VALUE:
n = input('ENTER THE VALUE FOR CALCULATING THE FACTORIAL: ');

% WHILE LOOP TO READ INPUT VALUES:
for i = 1:n

    % CALCULATE THE FACTORIAL:
    n_factorial = n_factorial * i;

end

%% GETTING THE RESULTS:

% INFORMING THE USER:
fprintf('THE FACTORIAL OF: %f', n);
fprintf('\nIS THE NUMBER: %f\n', n_factorial);
