%% CODING THE VAN DER POL SYSTEM EQUATIONS SOLUTION:
%  FREDERICO ANTONIAZZI - 14/08/2024

% USING KRYLOV-BOGULIOBOV METHOD FOR SMALL PERTURBATIONS
% SOLVING THE PARAMETER A IN VAN DER POL EQUATION

function xdot = aSolutionKB(t, x, epsilon)

xdot = epsilon/2*(x(1) - x(1)^3/2);