%% FREDERICO CASARA ANTONIAZZI
%  CODE FOR CALCULATING THE MEAN AND THE STANDART DEVIANTION OF A INPUT DATA SET
%  TENTH CODE IN PROGRAMMING WITH MATLAB OF CHAPMAN SECOND EDITION

%% INITIAL DEFINITIONS:

clear
close all
clc

format short

%% PURPOSE OF THE CODE:

% CALCULATE MEAN AND STANDART DEVIATION OF AN INPUT DATA SET CONTAINING AN
% ARBITRARY NUMBER OF INPUT VALUES.

% VARIABLES:
%   n       -> THE NUMBER OF INPUT SAMPLES
%   std_dev -> THE STANDART DEVIATION OF THE INPUT SAMPLES
%   sum_x   -> THE SUM OF THE INPUT VALUES
%   sum_x2  -> THE SUM OF THE SQUARES OF THE INPUT VALUES
%   x       -> AN INPUT DATA SAMPLE
%   xbar    -> THE AVERAGE OF THE INPUT SAMPLES

%% MAIN CODE:

n = 0;      % THE NUMBER OF SAMPLES
sum_x = 0;  % THE TOTAL SUM OF THE VALUE OF THE ELEMENTS OF THE DATA SET
sum_x2 = 0; % THE TOTAL SUM OF THE SQUARES OF THE ELEMENTS IN THE DATA SET

% READ IN FIRST VALUE:
x = input('ENTER THE FIRST VALUE: ');

% WHILE LOOP TO READ INPUT VALUES:
while x >= 0

    n = n + 1;
    sum_x = sum_x + x;
    sum_x2 = sum_x2 + x^2;

    % READ IN NEXT VALUE:
    x = input('ENTER NEXT VALUE: ');

end

% if n < 2
% 
%     % RESOLVING THE PROBLEM WHEN THERE IS NO SUFFICIENT INFORMATION TO DO
%     % THE CALCULATIONS AND A ZERO DIVISION WILL APPEAR
%     disp('INSUFFICIENT INFORMATION!');
%     disp('AT LEAST 2 VALUES MUST BE ENTERED!');
% 
% else

    % CALCULATE THE MEAN AND STANDART DEVIATION:
    xbar = sum_x/n;
    std_dev = sqrt((n*sum_x2 - sum_x2)/(n*(n - 1)));

    % INFORMING THE USER:
    fprintf('THE MEAN OF THIS DATA SET IS: %f\n', xbar);
    fprintf('THE STANDART DEVIATION OF THIS DATA SET IS: %f\n', std_dev);
    fprintf('THE NUMBER OF DATA POINTS IS: %f\n', n);

end
